apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: FROM ghcr.io/2022-4400-exp/4445-go-helloworld-2:53d5ca96a172e35a8ead7e3dbcdf819c33154744
        name: go-helloworld-2